version: '3'

services:

  rabbitmq:
    image: rabbitmq:management
    ports:
     - "15672:15672"
     - 5672:5672
    environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=kar.95424

  ingressapi:
     image: docker08.onedirectdev.in:5000/ingressapi:gcp-production
     ports:
       - 8080
     environment:
      - VIRTUAL_HOST=/ingressapi/*
      - CATALINA_OPTS=-Xmx1g -Xms1g -XX:MaxPermSize=128m
     extra_hosts:
      - "mysql:172.16.1.111"
      - "mysqlslave:172.16.1.111"
      - "redis:172.16.0.25"

  nginx:
    image: nginx:1.11-alpine
    depends_on:
      - kong
    volumes:
       - ./nginx/:/etc/nginx/
       - ./cache:/var/nginx/cache
       - ./ssl:/ssl
    ports:
       - "80:80"
       - "443:443"
    environment:
       - NGINX_PORT=80

  akoshav3:
    image: docker08.onedirectdev.in:5000/akoshav3:gcp-production
    ports:
       - 8080
    environment:
       - VIRTUAL_HOST=*/static/*,/util/*,*/admin,/admin/*,/admin/,/,*/OD-Admin/*,/brand,/brandfull,/brand-dashboard/*,/dominos*

  onedirectui:
    image: docker08.onedirectdev.in:5000/onedirectnewui:html-view
    ports:
       - 44004
    environment:
       - VIRTUAL_HOST=*/v2/*
  #onedirectui:
    #image: docker08.onedirectdev.in:5000/onedirectnewui:odb2-18262-tw-integration
    #ports:
       #- 44004
    #environment:
       #- VIRTUAL_HOST=*/v2/*

  auth:
    image: docker08.onedirectdev.in:5000/auth:production
    ports:
      - 8080
    environment:
     - VIRTUAL_HOST=/auth/*
     - CATALINA_OPTS=-Xmx256m -Xms256m -XX:MaxPermSize=128m
    extra_hosts:
     - "mysql:172.16.1.111"
     - "mysqlslave:172.16.1.111"
     - "redis:172.16.1.114"

  brandapi:
    image: docker08.onedirectdev.in:5000/brandapi:az-prod
    ports:
      - 8080
    environment:
     - VIRTUAL_HOST=/brandapi/*
     - CATALINA_OPTS=-Xmx256m -Xms256m -XX:MaxPermSize=128m
     - kafkaport=9092
     - kafkahost=172.16.0.26
    extra_hosts:
     - "mysql:172.16.1.105"
     - "mysqlslave:172.16.1.105"
     - "redis:172.16.1.109"
     - "haproxy:172.16.1.108"

  bsp-ui:
    image: docker08.onedirectdev.in:5000/bsp-ui:bsp-2fa
    ports:
     - 22009
    environment:
     - VIRTUAL_HOST=/bsp/*
     - HTTP_CHECK=/bsp/status

  isapi:
    image: docker08.onedirectdev.in:5000/isapi:timezoneSupport
    ports:
      - 8080
    environment:
     - VIRTUAL_HOST=/isapi/*
     - CATALINA_OPTS=-Xmx512m -Xms512m -XX:MaxPermSize=128m
    extra_hosts:
     - "mysql:172.16.1.105"
     - "mysqlslave:172.16.1.109"
     - "redis:172.16.1.109"
     - "rabbitmq:172.16.1.108"
     - "haproxy:172.16.1.108"


  ssoui:
    image: docker08.onedirectdev.in:5000/onedirectssoui:az-prod
    ports:
     - 33004:33004
    environment:
     - VIRTUAL_HOST=/sso/*
     - HTTP_CHECK=/sso/status
    extra_hosts:
     - "haproxy:172.16.1.108" 

  msg-ui:
    image: docker08.onedirectdev.in:5000/msg-ui:az-prod
    ports:
     - 22002
    environment:
     - VIRTUAL_HOST=/messaging/*
     - HTTP_CHECK=/messaging/status




  kong-database:
    image: postgres:9.4
    ports:
      - 5432
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  kong-migration:
    image: kong:0.10.0
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up

  kong:
    image: kong:0.10.0
    ports:
      - 8443:8443
      - 8000:8000
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    depends_on:
      - kong-database
      - kong-migration
    environment:
     - KONG_DATABASE=postgres
     - KONG_PG_HOST=kong-database

  kongui:
    image: pgbi/kong-dashboard:v2.3.1
    depends_on:
      - kong
    ports:
      - 8080:8080
  

  whatsapp:
     image: docker08.onedirectdev.in:5000/whatsapp:az-prod
     ports:
      - 8080
     environment:
      - VIRTUAL_HOST=/whatsapp/*
      - HTTP_CHECK=GET /whatsapp/status
      - CATALINA_OPTS=-Xmx512m -Xms512m -XX:MaxPermSize=128m
     extra_hosts:
      - "mysql:172.16.1.111"
      - "mysqlslave:172.16.1.111"
      - "redis:172.16.1.109"

  msg-chat-api:
    image: docker08.onedirectdev.in:5000/msg-chat-service:az-prod
    ports:
      - 8080
    environment:
     - VIRTUAL_HOST=/chat-msg/*
     - CATALINA_OPTS=-Xmx512m -Xms512m -XX:MaxPermSize=128m
     - kafkaport=9092
     - kafkahost=172.16.0.26
    extra_hosts:
     - "mysql:172.16.1.111"
     - "mysqlslave:172.16.1.111"
     - "redis:172.16.1.109"
     - "haproxy:172.16.0.28"

  wifeapi:
    image: docker08.onedirectdev.in:5000/wifeapi:az-prod
    ports:
     - 3000
    environment:
     - VIRTUAL_HOST=/wifeapi/*
    extra_hosts:
     - "mysql:172.16.1.111"
     - "mysqlslave:172.16.1.111"
     - "redis:172.16.1.109"
  
  haproxy:
    image: dockercloud/haproxy:1.5.2
    links:
      - brandapi
      - whatsapp
      - bsp-ui
      - msg-chat-api
      - ssoui
      - msg-ui
      - isapi
      - onedirectui
      - akoshav3
    environment:
      - STATS_AUTH=admin:kar.95424
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9080:80
      - 1936:1936
